[package]
name = "socket-io-rust"
version = "0.1.0"
authors = ["Chenxi Yuan <yuanchenxi95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
